### ISSUE TITLE
importing problem

### ISSUE THREAD

**Issue by dajingjing290** [cerr/CERR#199]
I got both this ioexception problem on both mac and windows pc.Could anyone help me with it?

CERR>>  Scanning DICOM directory
/Users/wangjingjing/Downloads
java.io.IOException
	at sun.awt.image.GifImageDecoder.readHeader(GifImageDecoder.java:322)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:119)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

**Comment by rkpandya** [comment]
Hi dajingjing290,

The java awt related messages are related to Matlab graphics. They should not affect the data import. 

-Rutu
