### ISSUE TITLE
CERR Converstion of RT/ROI DICOM Files

### ISSUE THREAD

**Issue by dansmith8881234** [cerr/CERR#213]
When I try to convert a RT file separate from a PT dicom file I get this output and error message. 

java.io.IOException
	at sun.awt.image.GifImageDecoder.readHeader(Unknown Source)
	at sun.awt.image.GifImageDecoder.produceImage(Unknown Source)
	at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at sun.awt.image.ImageFetcher.run(Unknown Source)
 Reading header ... 
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.sponsorID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.protocolID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.subjectID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.submissionID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.timeSaved field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.lastSavedInVer field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.CERRImportVersion field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.anonymizedID field, leaving empty.
 Reading comment ... 
 Reading scan ... 
 Reading structures ... 
 Reading structureArray ... 
 Reading structureArrayMore ... 
 Reading beams ... 
 Reading beamGeometry ... 
 Reading dose ... 
 Reading DVH ... 
 Reading IVH ... 
 Reading planParam ... 
 Reading seedGeometry ... 
 Reading digitalFilm ... 
 Reading RTTreatment ... 
 Reading IM ... 
 Reading GSPS ... 
 Reading deform ... 
 Reading registration ... 
 Reading texture ... 
 Reading featureSet ... 
 Reading importLog ... 
 Reading segmentLabel ... 
 Reading CERROptions ... 
 Reading indexS ... 
Index exceeds the number of array elements (0).
Error in sortStructures (line 56)
    if isObliqScanV(scanInd)  % strcmpi(modality,'mr')
Error in dcmdir2planC (line 349)
    planC{indexS.structures}(i) = sortStructures(planC{indexS.structures}(i),...
Error in CERRImportDCM4CHE (line 133)
    planC = dcmdir2planC(combinedDcmdirS);
Error in CERR (line 168)
                    CERRImportDCM4CHE;
Error while evaluating UIControl Callback.

**Comment by adityaapte** [comment]
Can you share your anonymized data?

**Comment by dansmith8881234** [comment]
[2.16.840.1.114362.1.11725706.21936055877.478056014.257.692.dcm.zip](https://github.com/cerr/CERR/files/2617136/2.16.840.1.114362.1.11725706.21936055877.478056014.257.692.dcm.zip)
